kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
      containers:
        - name: myspringbootapp
          image: saikumarpinisetti/jenkins-webhook:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9099
